In [19]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


##Introduction to Tensors

##Creating tensors

In [20]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [21]:
scalar.ndim

0

In [22]:
# Get tensor back as Python int
scalar.item()

7

In [23]:
# Vector
vector = torch.tensor ([7,7])
vector

tensor([7, 7])

In [24]:
vector.ndim

1

In [25]:
vector.shape

torch.Size([2])

In [26]:
#MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [27]:
MATRIX.ndim

2

In [28]:
MATRIX.shape

torch.Size([2, 2])

In [29]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [32]:
#Create a Random Tensors
random_tensor = torch.rand(3,4)
random_tensor

tensor([[1.4840e-01, 9.3140e-01, 5.9795e-01, 2.7883e-01],
        [9.1508e-01, 2.1308e-01, 9.6060e-01, 8.4807e-01],
        [1.3840e-04, 1.5882e-01, 3.5436e-01, 5.5122e-01]])

In [33]:
random_tensor.ndim

2

In [34]:
#Create a random tensor with similar shape to an image tenson
random_image_size_tensor = torch.rand(size=(3, 224, 224))#color channel(R, G, B), height, width
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([3, 224, 224]))

###zeros and ones

In [35]:
#create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [37]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [38]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [39]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor datatypes
Note : Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [40]:
##float 32 datatype
float_32_tensor = torch.tensor([3.0, 2.0, 4.0],
                               dtype = None,#what datatype is the tensor (e.g float32 or float16)
                               device = None, #what device is your tensor on
                               requires_grad = False) #whether or not to track  tensor gradient
float_32_tensor

tensor([3., 2., 4.])

In [41]:
float_32_tensor.dtype

torch.float32

In [42]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [43]:
float_16_tensor * float_32_tensor

tensor([ 9.,  4., 16.])

In [44]:
int_32_tensor = torch.tensor([3, 2 ,1], dtype = torch.int32)
int_32_tensor

tensor([3, 2, 1], dtype=torch.int32)

In [45]:
float_32_tensor * int_32_tensor

tensor([9., 4., 4.])

##Getting information from tensors (Tensor attributes)
1. Tensors not right datatype - to get datatype froom a tensor can use 'tensor.dtype'
2. Tensors not right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'

In [46]:
#create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7066, 0.0139, 0.6050, 0.6601],
        [0.8090, 0.9279, 0.4224, 0.2540],
        [0.3975, 0.6179, 0.8996, 0.6874]])

In [47]:
#Find out some details about some tensor
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor: {some_tensor.device}')

tensor([[0.7066, 0.0139, 0.6050, 0.6601],
        [0.8090, 0.9279, 0.4224, 0.2540],
        [0.3975, 0.6179, 0.8996, 0.6874]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include :
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [48]:
#Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [49]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [50]:
#subtract 10
tensor - 10

tensor([-9, -8, -7])

In [51]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [52]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning

1. Element-wise multiplication
2. Matrix-wise multiplication (dot product)

There are to main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match :
* (3,2) @ (3,2) won't work
* (2,3) @ (3,2) will work
* (3,2) @ (2,3) will work

2. The resulting matrix has the shape of the **outer dimenstions**
* (2,3) @ (3,2) -> (2,2)
* (3,2) @ (2,3) -> (3,3)


In [53]:
torch.matmul(torch.rand(3,3) , torch.rand(3,2))

tensor([[1.2511, 0.9839],
        [0.7727, 0.6370],
        [0.7775, 0.6255]])

In [54]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [55]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [56]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.4 ms, sys: 0 ns, total: 1.4 ms
Wall time: 1.83 ms


In [57]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 300 µs, sys: 0 ns, total: 300 µs
Wall time: 263 µs


tensor(14)

### One of the most common errors

In [58]:
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor_B = torch.tensor([[7, 10],[8, 11],[9,12]])

torch.mm(tensor_A, tensor_B) #torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose

A transpose switches the axis or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

In [ ]:
tensor_B.T, tensor_B.T.shape

In [ ]:
torch.matmul(tensor_A,tensor_B.T)

##Finding the min, max, mean, sum, etc(tensor aggregator)

In [ ]:
#create a tensor
x = torch.arange(0,100,10)
x

In [ ]:
torch.min(x)

In [ ]:
torch.max(x)

In [ ]:
#the function requires a tensor of float32 datatype
torch.mean(x.type(torch.float32))

In [ ]:
torch.sum(x)

#Finding the position min and max

In [ ]:
#Find the position of where the values are.
torch.argmin(x)

In [ ]:
torch.argmax(x)

## Reshaping, stacking, squeeing and unsqueeing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory of the original tensor
* Stacking - combines multiple tensors on tip of each other (vstack) or side by side (hstack)
* squeee - removes all 1 diemsnions from a tensor
* unsqueee - add a 1 dimension to a target tensor
* permute - Return a view of the input with dimension perumted(swapped) in a certain way

In [ ]:
# create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

In [ ]:
y = x.view(1,9)
x[0] = 3
x, y

In [ ]:
y, y.shape

In [ ]:
#torch.squeeze() - removes all single dimension from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#REmove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

In [ ]:
#torch.permute - rearranges the dimensions of a target tensor in a specified format
x_original = torch.rand(244,244,3) #[height, width , color_channels]

#perumte the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # []

In [ ]:
x_original

#Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [ ]:
#Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
x[0]
x[0,1]
x[0][0][2]

In [ ]:
#You can also use ": "to slelect "all of a target dimension"
x[:,0]

In [ ]:
#Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

In [ ]:
x[:, 1, 1]

In [ ]:
x[0, 0, :]

In [ ]:
x[:, 2, 2]

# PyTorch tensors & Numpy
Numpy is a popular scientific python numerical computing library
And becayse of this, PyTorch has funcionality to interact with it.
* Data in Numpy , want in Pytorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> Numpy -> torch.Temsor.numpy{}

In [ ]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #when converting from numpy to pytorch, pytorch reflects numpy's default datatype float64
array, tensor

In [ ]:
# Tensor to numpy array
tensor = torch.arange(1,8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

## Reproducibility (trying to take the random out of random)
In short how a neural network learns:

start with random numbers -> tensor operations _> update random numbers to try
to make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
torch.rand(3,4)

In [ ]:
import torch
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

In [ ]:
#Let.s make some random but reproducible tensors
import torch

#Set the random seed
RANDOM_SEED = 42

#call the torch.manual_seed(RANDOM_SEED) everytime you want to call your random tensors
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


In [ ]:
#Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

In [ ]:
#count number of devices
torch.cuda.device_count()

## Putting tensors (and models) on the GPU

the reason we want our tensors/models on the GPU is because using a GPU is for faster computing

In [ ]:
#create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPU
print(tensor, tensor.device)

In [ ]:
#Move tensor to GPu (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

Moving tensors back to the CPU

In [ ]:
#If tensors is on GPU, cant transform to Numpy
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

In [ ]:
## Exercises & Extra-Curriculum

In [ ]:
!git config --global user.email tobilobaayodele23@gmail.com
!git config --global user.name Darkdev007

In [ ]:
!git init

In [ ]:
!git branch -M main

In [ ]:
!git remote add origin https://github.com/Darkdev007/DEEP-LEARNING.git

In [ ]:
!git add .

In [ ]:
!git commit -m "Initial commit"

In [ ]:
!git push -u origin main

In [ ]:
!git config --global user.name
!git config --global user.email


In [ ]:
!git remote -v

In [ ]:
!git push -u origin main


In [ ]:
!git remote set-url origin https://Darkdev007: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@github.com/Darkdev007/DEEP-LEARNING.git

In [ ]:
!git push origin main


In [59]:
!git rm -r --cached .

rm '.config/.last_opt_in_prompt.yaml'
rm '.config/.last_survey_prompt.yaml'
rm '.config/.last_update_check.json'
rm '.config/active_config'
rm '.config/config_sentinel'
rm '.config/configurations/config_default'
rm '.config/default_configs.db'
rm '.config/gce'
rm '.config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db'
rm '.config/logs/2025.11.05/14.33.13.470069.log'
rm '.config/logs/2025.11.05/14.33.36.385956.log'
rm '.config/logs/2025.11.05/14.33.44.287731.log'
rm '.config/logs/2025.11.05/14.33.45.559498.log'
rm '.config/logs/2025.11.05/14.33.53.434728.log'
rm '.config/logs/2025.11.05/14.33.54.129583.log'
rm 'sample_data/README.md'
rm 'sample_data/anscombe.json'
rm 'sample_data/california_housing_test.csv'
rm 'sample_data/california_housing_train.csv'
rm 'sample_data/mnist_test.csv'
rm 'sample_data/mnist_train_small.csv'


In [60]:
!git add 00_pytorch_fundamentals_video.ipynb

fatal: pathspec '00_pytorch_fundamentals_video.ipynb' did not match any files


In [61]:
!pwd


/content


In [67]:
%cd /content/sample_data

/content/sample_data


In [68]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [63]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [69]:
%cd /content/drive
!ls


/content/drive
MyDrive


In [70]:
from google.colab import files
uploaded = files.upload()  # This will open a file picker


Saving 00_pytorch_fundamentals_video.ipynb to 00_pytorch_fundamentals_video.ipynb


OSError: [Errno 95] Operation not supported: '00_pytorch_fundamentals_video.ipynb'

In [71]:
from google.colab import files
uploaded = files.upload()


Saving 00_pytorch_fundamentals_video.ipynb to 00_pytorch_fundamentals_video.ipynb


OSError: [Errno 95] Operation not supported: '00_pytorch_fundamentals_video.ipynb'

In [73]:

from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [76]:
%cd /content/drive/MyDrive/Colab Notebooks  # adjust path if needed
!ls


[Errno 2] No such file or directory: '/content/drive/MyDrive/Colab Notebooks # adjust path if needed'
/content/drive
MyDrive


In [75]:
!ls /content/drive/MyDrive


'2025 AIRDROP.gsheet'
'2210096 assignment1.docx'
'2210096 assignment2b.docx'
'Aidrops 2024 beginning march.gsheet'
'AYODELE OLUWATOBILOBA JOSHUA 180401009.gsheet'
"AYODELE OLUWATOBILOBA JOSHUA'S RESUME.docx"
"AYODELE OLUWATOBILOBA JOSHUA'S RESUME.gdoc"
'Birth certificate.jpg'
 btre_resources.zip
'CHM 212'
'CHM 213'
'Colab Notebooks'
'Cover letter template.gdoc'
 D4F5A820-EB0F-45E1-A0AE-9C3A048C28C0.png
'EEG 211'
'Embarcadero_Dev-Cpp_6.3_TDM-GCC 9.2_Setup.exe'
'Essay for Glorious.gdoc'
'ESSENTIAL BIOCHEM EXAM REVISION 2.gdoc'
 F257F9BE-6020-43FD-AED5-C3741743AA02.png
'GEG 217'
'GEG 219'
'Getting started.pdf'
 GST
'HEXAVIAN REPORT FOR 13TH APRIL 2021.xlsx.gsheet'
'HEXAVIAN REPORT FOR 16TH OF APRIL 2021.xlsx.gsheet'
'HEXAVIAN REPORT FOR 19TH MARCH 2021.xlsx'
'HEXAVIA REPORT FOR 9TH APRIL 2021.xlsx.gsheet'
'Hostel balloting form.gform'
 IMG_0447.png
 IMG_0449.png
 IMG_2832.jpeg
 IMG_9153.png
 IMG_9154.png
'Jamb original result.jpg'
'KNOW THE TERMS WE USE IN CRYPTO.gdoc'
 MMASSIGNMENT.docx


In [77]:
%cd "/content/drive/MyDrive/Colab Notebooks"
!ls


/content/drive/MyDrive/Colab Notebooks
 00_pytorch_fundamentals_video.ipynb
 01_pytorch_workflow_video.ipynb
 02_neural_network_classification_with_pytorch_video.ipynb
 02_PyTorch_Training.ipynb
 03_pytorch_computer_vision_video.ipynb
 04_PyTorch_Custom_Datasets_Video.ipynb
 05_pytorch_going_modular_cell_mode_video.ipynb
'06 Excercise Transfer Learning.ipynb'
 06_PyTorch_Transfer_Learning.ipynb
 07_Pytorch_Experiment_Tracking.ipynb
 08_pytorch_paper_replicating_video.ipynb
 09_pytorch_model_deploy_video.ipynb
 cisco_lab.ipynb
'Collab File.ipynb'
'Computer Vision Training 2.ipynb'
'Computer Vision Training.ipynb'
'Curved Line model.ipynb'
'Custom Dataset.ipynb'
'Custom dataset Training.ipynb'
'Experiment Tracking.ipynb'
'Going Modular.ipynb'
'Going Modular Training.ipynb'
'Object detection and Segmentation 2.ipynb'
'Object detection and segmentation.ipynb'
'Paper replicating training.ipynb'
 Putting_everything_together.ipynb
'PyTorch Transfer Learning.ipynb'
'Training_00. PyTorch Fundam

In [79]:
%cd /content

/content


In [80]:
!git init

Reinitialized existing Git repository in /content/.git/


In [83]:
!git add "00_pytorch_fundamentals_video.ipynb"

fatal: pathspec '00_pytorch_fundamentals_video.ipynb' did not match any files


In [84]:
from shutil import copyfile
source_path = "/content/drive/MyDrive/Colab Notebooks/00_pytorch_fundamentals_video.ipynb"
destination_path = "/content/00_pytorch_fundamentals_video.ipynb"
copyfile(source_path, destination_path)

'/content/00_pytorch_fundamentals_video.ipynb'

In [85]:
%cd /content
!ls

/content
00_pytorch_fundamentals_video.ipynb  drive  sample_data


In [86]:
!git add "00_pytorch_fundamentals_video.ipynb"

In [87]:
!git commit -m "Pytorch fundamental 00 notebook"

[main a67a8db] Pytorch fundamental 00 notebook
 22 files changed, 1 insertion(+), 51025 deletions(-)
 delete mode 100644 .config/.last_opt_in_prompt.yaml
 delete mode 100644 .config/.last_survey_prompt.yaml
 delete mode 100644 .config/.last_update_check.json
 delete mode 100644 .config/active_config
 delete mode 100644 .config/config_sentinel
 delete mode 100644 .config/configurations/config_default
 delete mode 100644 .config/default_configs.db
 delete mode 100644 .config/gce
 delete mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 delete mode 100644 .config/logs/2025.11.05/14.33.13.470069.log
 delete mode 100644 .config/logs/2025.11.05/14.33.36.385956.log
 delete mode 100644 .config/logs/2025.11.05/14.33.44.287731.log
 delete mode 100644 .config/logs/2025.11.05/14.33.45.559498.log
 delete mode 100644 .config/logs/2025.11.05/14.33.53.434728.log
 delete mode 100644 .config/logs/2025.11.05/14.33.54.129583.log
 create mode 100644 00_pytorch_fundamentals

In [88]:
!git push -u origin main


Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 14.99 KiB | 1.15 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH013: Repository rule violations found for refs/heads/main.
remote: 
remote: - GITHUB PUSH PROTECTION
remote:   —————————————————————————————————————————
remote:     Resolve the following violations before pushing again
remote: 
remote:     - Push cannot contain secrets
remote: 
remote:     
remote:      (?) Learn how to resolve a blocked push
remote:      https://docs.github.com/code-security/secret-scanning/working-with-secret-scanning-and-push-protection/working-with-push-protection-from-the-command-line#resolving-a-blocked-push
remote:     
remote:     
remote:       —— GitHub Personal Access Token ——————————————————————
remote:        locations:
remote:          - commit: a67a8db86ddfb7ae01eae7c447cbc885253bb58c


In [89]:
!git reset --hard HEAD~1


HEAD is now at 48664f2 Initial commit


In [90]:
!git add "00_pytorch_fundamentals_video.ipynb"
!git commit -m "Add cleaned notebook without secrets"


fatal: pathspec '00_pytorch_fundamentals_video.ipynb' did not match any files
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	drive/

nothing added to commit but untracked files present (use "git add" to track)
